---
- name: Apply the AXE Gitian builder role.
  become: yes
  hosts: localhost:axe-build
  vars:
    axe_git_repo_url: "{{ lookup('env','AXE_GIT_REPO_URL') }}"
    axe_version: "{{ lookup('env','AXE_VERSION') }}"
    git_name: "{{ lookup('env','GIT_NAME') }}"
    git_email: "{{ lookup('env','GIT_EMAIL') }}"
    gpg_key_name: "{{ lookup('env','GPG_KEY_NAME') }}"
    gpg_key_id: "{{ lookup('env','GPG_KEY_ID') }}"
  roles:
    - role: common
      tags: common
    - role: gitian
      tags: gitian
