---
- name: Apply the AXE Gitian builder role.
  become: yes
  hosts: localhost:axe-build
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  vars:
    axe_git_repo_url: https://github.com/AXErunners/axe
    gpg_key_name: '8DFCBF8E5A4D8019'
    git_name: 'Duke Leto'
    git_email: 'duke@leto.net'
    axe_version: v1.1.8
    # optional - auto imports private key necessary for signing
    gpg_key_id: '8DFCBF8E5A4D8019'
    # optional
    ssh_key_name: ''
  roles:
    - role: common
      tags: common
    - role: gitian
      tags: gitian
