---
axe_swapfile_size: 2G
axe_vm_swappiness: 1
axe_common_packages:
  - apt-show-versions
  - apt-transport-https
  - curl
  - git
  - haveged
  - htop
  - ntp
  - ntpdate
  - python-pip
  - rsync
  - screen
  - sudo
  - tmux
  - tree
  - vim
